[[redirects]]
  from = "/booking"
  to = "https://calendar.app.google/dRiTMZYMWCyUv5xv9"
  status = 301

[[redirects]]
  from = "/chooning-ringo-fes-2025"
  to = "https://ringofes.info/?from=chooning"
  status = 200

[build]
  image = "ubuntu-22.04"
  command = "rm -rf public && cd scripts && npm install && cd .. && node scripts/contentful-to-markdown.js && hugo --gc --minify"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.132.1"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.132.1"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.132.1"